var bintro = new Array();
bintro[0] = "null";
bintro[1] = "一个中学立体几何问题的背后隐藏着Bosuk-Ulam定理.";
bintro[2]= "详细展示了Dvir的proof from the Book.";
bintro[3] = "Grownwall不等式的一个非传统证明.";
bintro[4] = "用微分流形的语言自然地将定理与Stokes公式联系起来."
bintro[5] = "将分析对象随机化的一个美妙范例.";
bintro[6] = "令人惊喜的试题，深刻的研究背景.";
bintro[7] = "Bourgain的两个好工具：定量化和抽屉原理.";
bintro[8] = "纪念H. Brezis，介绍一道实分析经典习题的背景.";
bintro[9] = "记录一个内积不等式.";
bintro[10] = "来自统计物理的计算题，一个漂亮的观察.";
bintro[11] = "等宽曲线的Barbier定理，以及Crofton公式的一个分析式证明.";
bintro[12] = "讨论Sobolev嵌入的紧性缺失，叙述了bubble decomposition.";
bintro[13] = "用频率精细化的Sobolev不等式确定大bubble, 并建立迭代格式.";
bintro[14] = "以格论的语言叙述了一个清爽、直观的证明.";
bintro[15] = "基于不动点证明给出直接构造双射的算法.";
bintro[16] = "球面的测地线；正交性的应用；重整化(baby ver) .";
bintro[17] = "PDE, 调和分析与数论的美妙联系，Fourier decoupling的先声.";
bintro[18] = "随机化的思想和尺度分离-平均的技巧."
// bintro[] = "";
